version: "3"
services:

  nginx:
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php7.2"
      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/vhost/:/etc/nginx/vhost/
        - ../:/datadisk/website/
      container_name: nginx

  mysql:
      #image: mysql:5.7.21
      image: mysql:5.5.60
      ports:
        - "3306:3306"
      expose:
        - "3306"
      volumes:
        #- ./conf/my.cnf:/etc/mysql/my.cnf
        - ../:/datadisk/website
        - ./mysql/:/var/lib/mysql/

      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      container_name: mysql


#  redis:
#      image: redis:4.0.8
#      ports:
#        - "6379:6379"
#      expose:
#        - "6379"
#      volumes:
#        - ./conf/redis.conf:/etc/redis.conf
#        - ../:/datadisk/website
#      command: "redis-server /etc/redis.conf"
#
#      container_name: redis


  php7.2:
      build:
        ./php7.2/
      ports:
        - "9000:9000"
      expose:
        - "9000"
      links:
#        - "redis"
        - "mysql"
      volumes:
        - ../:/datadisk/website
#        - ../meitu_local_config/:/www/privdata/
#        - ./php7.2/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#        使用自己的配置文件，将下面几行注释取消掉
#        - ./php7.2/php.ini-production:/usr/local/etc/php/php.ini
#        - ./php7.2/php-fpm.conf:/usr/local/etc/php-fpm.conf
#        - ./php7.2/php-fpm.d/:/usr/local/etc/php-fpm.d/
      container_name: php7.2

